# SciPy

SciPy представляет собой совокупность математических алгоритмов и функций, построенных как расширение Numpy на Python. Он значительно расширяет возможности интерактивной сессии Python, предоставляя пользователю команды высокого уровня и классы для управления и визуализации данных. Со SciPy интерактивный сеанс Python становится средой обработки данных и системой прототипирования соперничающей с такими системами, как MATLAB, IDL, Octave, R-Lab, and SciLab.

*Модули SciPy*:

* constants - Физические константы и коэффициенты пересчёта 

* cluster - Векторное квантование

* fftpack - Дискретные алгоритмы преобразования Фурье 

* integrate - Инструменты для интегрирования 

* interpolate - Инструменты для интерполяции 

* io - Ввод-вывод данных 

* lib - Работа со сторонними библиотеками 

* linalg - Линейная алгебра 

* optimize - Средства оптимизации 

* sandbox - Экспериментальный код 

* signal - Обработка сигналов 

* sparse - Поддержка разреженных матриц 

* special - Специальные функции

* stats - Статистические функции 

* weave - Использование кода, написанного на языках C и C++

In [20]:
# подключим необходимые в дальнейшем модули
import numpy as np


## Подмодуль linalg

Модуль linalg предназначен для реализации линейной алгебры.

In [21]:
from scipy import linalg 

**Метод dot(a,b)**

Матричное умножение a × b.


In [22]:
A = np.array([[ 1., 1., 1., 1.], [ 1., 1., 1., 1.], [ 1., 1., 1., 1.],[ 1., 1., 1., 1.]])
print('A:')
print(A)
B = np.array([[ 1., 1.], [ 1., 1.], [ 1., 1.], [ 1., 1.]])
print('B:')
print(B)

q = np.dot(A, B)
print(q)

A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
B:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


**Метод solve(a,b)**

Задача: нужно найти такой x, что, если матрицу a умножить на x, то получится матрица b.

In [23]:
a = np.array([[3, 2, 0],[1, -1, 0],[0, 5, 1]])
print('a:')
print(a)
b = np.array([2, 4, -1])
print('b:')
print(b)
x = linalg.solve(a,b)
print('x =',x)

a:
[[ 3  2  0]
 [ 1 -1  0]
 [ 0  5  1]]
b:
[ 2  4 -1]
x = [ 2. -2.  9.]


In [24]:
np.dot(a, x) # Проверим - результат должен быть равен b

array([ 2.,  4., -1.])

**Метод det(m)**

Нахождение определителя матрицы.

In [25]:
B = np.array([[-4, -1, 2], [10, 4, -1], [8, 3, 1]])
print(B)
q = np.linalg.det(B)
print(q)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
-14.000000000000009


**Метод svd(x)**

Сингулярное разложение матрицы.

In [7]:
x = np.random.randn(4, 3)
print('x:')
print(x)
U, D, V = linalg.svd(x)
print (U.shape, D.shape, V.shape)
print (type(U), type (D), type(V))

x:
[[-0.1472416  -0.24669754  0.61122716]
 [ 0.75507772  1.37491485 -0.50868729]
 [ 0.19862968  2.06707627 -0.25011693]
 [ 0.49005284  1.34922733 -0.77283106]]
(4, 4) (3,) (3, 3)
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


## Подмодуль optimize

In [8]:
from scipy import optimize # подмодуль optimize

В модуле optimize есть **метод minimize**, которому достаточно передать функцию, передать начальное приближение. Мы видим, что значение функции равно примерно 2 в точке с  координатами x: array([-1.03529084e-07,  4.99997747e+00]), которые с достаточно высокой степенью точности совпадают с правильными. 

In [9]:
def f(x):
    return 3**(x[0]**2) + 3**(1e-8*x[1]**2)

x_min = optimize.minimize(f, [-5, 5])
print(x_min)

      fun: 2.000000274650647
 hess_inv: array([[ 4.54979753e-01, -8.89864272e-06],
       [-8.89864272e-06,  1.00000000e+00]])
      jac: array([-2.38418579e-07,  8.94069672e-08])
  message: 'Optimization terminated successfully.'
     nfev: 164
      nit: 36
     njev: 41
   status: 0
  success: True
        x: array([-1.03529084e-07,  4.99997747e+00])


Если нужна только точка минимума, можно обратится к полю X нужного объекта

In [10]:
print(x_min.x)

[-1.03529084e-07  4.99997747e+00]


## Подмодуль integrate

In [26]:
import scipy.integrate as integrate # подмодуль integrate

**Функция quad** предназначена для интегрирования функции одной переменной между двумя точками. 
Точки могут быть (inf), чтобы указать бесконечные пределы. Например, предположим, что вы хотите интегрировать функцию 
Бесселя jv (2.5, x) вдоль интервала [0,4.5]

In [27]:
import scipy.special as special
result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)
print(result)


(1.1178179380783253, 7.866317182537226e-09)


**Метод root**

В следующем примере рассматривается трансцендентное уравнение с одной переменной
x * x + 2cos (x) = 0.

Корень уравнения можно найти следующим образом.

In [13]:
from scipy.optimize import root
def func(x):
    return x*2 + 2 * np.cos(x)
sol = root(func, 0.3)
print(sol)

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 10
     qtf: array([-2.77666778e-12])
       r: array([-3.3472241])
  status: 1
 success: True
       x: array([-0.73908513])


## sparse - Поддержка разреженных матриц

Работа с большими разреженными матрицами в Python: десятки миллионов элементов = 10^4 x 10^4. Пример - исходная матрица не помещается в ОЗУ:

https://docs.scipy.org/doc/scipy/reference/sparse.html


In [28]:
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import spsolve
from numpy.linalg import solve, norm
from numpy.random import rand

In [15]:
n = 1000

Создадим матрицу 1000x1000 lil_matrix (lil = list of lists):

In [16]:
A = lil_matrix((n, n))
A[0, :100] = rand(100)
A[1, 100:200] = A[0, :100]
A.setdiag(rand(n))

Преобразуем ее к формату CSR и решим A*x = b:

In [17]:
A = A.tocsr()
b = rand(n)
print(len(b))
x = spsolve(A, b)

1000


Преобразуем матрицу к неразреженной, решим, и проверим, что результаты совпадают:

In [18]:
x_ = solve(A.toarray(), b)

Теперь вычислим норму ошибки (ответы почти не отличаются):

In [19]:
err = norm(x-x_)
err < 1e-10

True

In [2]:
from scipy.sparse import rand
import numpy
from datetime import datetime

In [20]:
n = 10000
A = rand(n, n, density=0.25, format="csr")
b = numpy.random.rand(n)

In [21]:
len(b)

10000

In [28]:
type(b)

numpy.ndarray

In [26]:
A[3,0]

0.0

In [29]:
type(A)

scipy.sparse._csr.csr_matrix

In [30]:
A.shape

(10000, 10000)

In [6]:
import sys
 
sys.getsizeof(A)

56

In [31]:
sys.getsizeof(b)

80112

In [32]:
start_time = datetime.now()
x = spsolve(A, b)
print(datetime.now() - start_time)

0:05:28.389129


In [33]:
A = A.toarray()

In [34]:
sys.getsizeof(A)

800000128

In [35]:
start_time = datetime.now()
x_ = solve(A, b)
print(datetime.now() - start_time)

0:00:07.091625


In [36]:
err = norm(x-x_)
err < 1e-8

True

In [3]:
n = 20000
A = rand(n, n, density=0.25, format="csr")

In [4]:
b = numpy.random.rand(n)

In [7]:
sys.getsizeof(A)

56

In [8]:
A = A.toarray()

In [9]:
sys.getsizeof(A)

3200000128

In [10]:
sys.getsizeof(1111111111111111134)

32

In [29]:
x=3
id(x)

140708143338344

In [30]:
y=3
id(y)

140708143338344

In [31]:
x=5
id(x)

140708143338408

In [32]:
v=1+4
id(v)

140708143338408

In [15]:
x=256
id(x)

140708143346440

In [16]:
y=256
id(y)

140708143346440

In [17]:
x=-5
print(id(x))
y=-5
print(id(y))

140708143338088
140708143338088


In [18]:
x=257
print(id(x))
y=257
print(id(y))

3185016687856
3185016688816


In [19]:
x=-6
print(id(x))
y=-6
print(id(y))

3185016690000
3185016689488


In [34]:
id(-5)

140708143338088