In [8]:
import numpy as np

Задание № 1 - 1

In [10]:
A = np.matrix('2 -1; 3 2; 5 -2')
B = np.matrix('-2 -1; 11 -2; 5 7')
C = np.matrix('1 3 0 4; 0 2 -3 5; 5 3 10 -2')
D = np.matrix('-2 5 1 -3; 1 1 -5 -4; 2 6 11 -1')
G = (2*A + B).transpose().dot(3*C - 4*D)
print(G)

[[  59 -213  -31  545]
 [ -20   -8   -8  -16]]


Задание № 1 - 2

In [18]:
A = np.matrix('0 1 1 1; 1 0 1 1; 1 1 0 1; 1 1 1 0')
print(A)
print(f'Определитель матрицы: {np.linalg.det(A)}')

[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]
Определитель матрицы: -2.9999999999999996


Задание № 1 - 3

In [22]:
A = np.matrix('3 -5 9 3 -1 0; 5 -3 -5 0 -5 13; -6 10 -4 15 -2 0; 15 -6 9 -9 -2 -6; 8 -3 5 -5 8 -1; 0 8 6 -4 12 -7')
print(A)
print('Обратная матрица:')
print(np.linalg.inv(A))
print('Проверка:')
print(A * np.linalg.inv(A))

[[ 3 -5  9  3 -1  0]
 [ 5 -3 -5  0 -5 13]
 [-6 10 -4 15 -2  0]
 [15 -6  9 -9 -2 -6]
 [ 8 -3  5 -5  8 -1]
 [ 0  8  6 -4 12 -7]]
Обратная матрица:
[[-0.04208275  0.01724784  0.05829242  0.05465385  0.07124448 -0.02499224]
 [-0.00878783  0.0719964   0.0220256   0.04365973 -0.1070451   0.11157714]
 [ 0.11290944  0.04244897 -0.02917647  0.00451783 -0.09922493  0.08913637]
 [ 0.0171968  -0.03323073  0.0685683  -0.01310623  0.09032082 -0.06338327]
 [-0.01453377 -0.02588991  0.00786595 -0.05299531  0.12689703 -0.02078486]
 [ 0.05199451  0.09327272 -0.02553368 -0.02959057 -0.04146132  0.06165001]]
Проверка:
[[ 1.00000000e+00 -1.31838984e-16 -2.42861287e-17 -4.85722573e-17
   5.55111512e-17 -1.76941795e-16]
 [ 0.00000000e+00  1.00000000e+00 -1.66533454e-16  1.66533454e-16
  -2.22044605e-16  1.11022302e-16]
 [ 1.04083409e-16  2.35922393e-16  1.00000000e+00  8.32667268e-17
   0.00000000e+00  9.02056208e-17]
 [ 0.00000000e+00  0.00000000e+00 -5.55111512e-17  1.00000000e+00
  -2.77555756e-17  0.0000

Задание № 2

In [33]:
A = np.matrix('3 -5 9 3 -1 0; 5 -3 -5 0 -5 13; -6 10 -4 15 -2 0; 15 -6 9 -9 -2 -6; 8 -3 5 -5 8 -1; 0 8 6 -4 12 -7')
sz = np.linalg.eigvals(A)
print(sz)

[-17.04690349+0.j         -10.34701511+8.01817564j
 -10.34701511-8.01817564j  10.23710304+4.32845573j
  10.23710304-4.32845573j   5.26672763+0.j        ]
