In [1]:
import numpy as np

In [6]:
X0 = np.matrix([[1], [4], [7]])
y = np.matrix([5, 3, 1])
# Создаем матриицу из единиц
one_matrix = np.ones((3, 1))
print(one_matrix)
# Производим слияние матрицы one_matrix с матрицей Х
X = np.concatenate((one_matrix, X0),axis=1)
print(X)
# Умножаем транспонированную матрицу Х на матрицу Х
X_mult = np.transpose(X) * X
print(X_mult)
# Находим обратную матрицу полученного результата
X_inv = np.linalg.inv(X_mult)
print(X_inv)
# Умножаем обратную матрицу на транспонированную
X_mult_2 = X_inv * np.transpose(X)
print(X_mult_2)
# Находим значение весов, умножая полученный результат на матрицу у
w_opt = X_mult_2 * y.T
print(w_opt)

[[1.]
 [1.]
 [1.]]
[[1. 1.]
 [1. 4.]
 [1. 7.]]
[[ 3. 12.]
 [12. 66.]]
[[ 1.22222222 -0.22222222]
 [-0.22222222  0.05555556]]
[[ 1.          0.33333333 -0.33333333]
 [-0.16666667  0.          0.16666667]]
[[ 5.66666667]
 [-0.66666667]]
