In [28]:
import numpy as np

Задание № 1

In [24]:
A = np.matrix('-3 0.5 0.5; 0.5 -6 0.5; 0.5 0.5 -3')
B = np.matrix('-56.5; -100; -210')
X = np.linalg.solve(A, B)
for t, x in zip(X, ['x1 =', 'x2 =', 'x3 =']):
    print(x ,t)

#print(X)
print(A.dot(X) - B)

x1 = [[36.65763547]]
x2 = [[26.43103448]]
x3 = [[80.51477833]]
[[-1.42108547e-14]
 [ 1.42108547e-14]
 [-2.84217094e-14]]


In [15]:
# метод Крамера
d = np.linalg.det(A)
print(d)

s_0 = A[:, 0]
s_1 = A[:, 1]
s_2 = A[:, 2]

A_1 = np.column_stack((B, s_1, s_2))
d_1 = np.linalg.det(A_1)

A_2 = np.column_stack((s_0, B, s_2))
d_2 = np.linalg.det(A_2)

A_3 = np.column_stack((s_0, s_1, B))
d_3 = np.linalg.det(A_3)

x_1 = d_1 / d
x_2 = d_2 / d
x_3 = d_3 / d

print(f'Решение системы: {x_1}, {x_2}, {x_3}')

X = np.array([[x_1], [x_2], [x_3]])
#print(X)

print(A.dot(X) - B)

-50.74999999999998
Решение системы: 36.65763546798033, 26.431034482758637, 80.51477832512315
[[-9.23705556e-14]
 [-8.52651283e-14]
 [ 2.84217094e-14]]


In [34]:
# обратная матрица
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

print(A.dot(X) - B)

[[36.65763547]
 [26.43103448]
 [80.51477833]]
[[ 0.00000000e+00]
 [-1.42108547e-14]
 [-2.84217094e-14]]


In [ ]:
2	0	0,5	0,75	0	0	1	0,09	0	1,25	0,06
0	1,63	0	0	0	0	0	0,05	0	0	0,47
0,5	0	1,5	0,3	0	0	1	0	0	0	0,08
0,75	0	0,3	3,3	0,77	0	0,5	0	0	0	0,73
0	0	0	0,77	2,01	0	0	0	0	0	0,71
0	0	0	0	0	0,75	0	0	0	0	0,21
1	0	1	0,5	0	0	2,25	0	0	0,08	0,23
0,09	0,05	0	0	0	0	0	1,25	0	0,5	0,28
0	0	0	0	0	0	0	0	0,666	0,15	0,37
1,25	0	0	0	0	0	0,08	0,5	0,15	1,333	0,29