                                                             Бояринцев Дмитрий Федорович

#                                    Лабораторная работа №5

In [1]:
import random
import numpy as np

## Массивы Numpy

**1.** Сформировать одномерный массив, состоящий из n вещественных элементов co значением от -10 до 10.0. Для случайного числа y, такого, что *минимальный элемент массива < y < максимальный элемент массива*, вычислить:  
  
* произведение элементов массива, значения модуля которых больше модуля y,  
  
* сумму модулей остальных элементов.

In [2]:
while True:
    try:
        n = int(input("Введите положительное целое число: "))
        if n > 0:
            break
        else:
            print("Число должно быть больше 0! Попробуйте еще раз.")
    except ValueError:
        print("Некорректный ввод! Попробуйте еще раз.")

arr_f = np.array([random.uniform(-10, 10) for x in range(n)])
print(f"Массив из {n} случайных вещественных чисел из диапазона [-10; 10]")
print(arr_f)

min_arr_f = min(arr_f)
print(f"min = {min_arr_f}")

max_arr_f = max(arr_f)
print(f"max = {max_arr_f}")

y = random.uniform(min_arr_f, max_arr_f)
print(f"y = {y}")

p = 1
s = 0
for i in range(n):
    if abs(arr_f[i]) > abs(y):
        p *= arr_f[i]
    else:
        s += arr_f[i]
print(f"p = {p}, s = {s}")

Введите положительное целое число:  5


Массив из 5 случайных вещественных чисел из диапазона [-10; 10]
[ 5.4656603   0.69675318 -4.83015915 -6.73351953 -9.28730127]
min = -9.287301265251763
max = 5.465660297634582
y = -7.774193302218492
p = -9.287301265251763, s = -5.401265206370349


**2.** Найти максимальный элемент в одномерном массиве x среди элементов, перед которыми стоит нулевой.

In [3]:
while True:
    try:
        n = int(input("Введите положительное целое число: "))
        if n > 0:
            break
        else:
            print("Число должно быть больше 0! Попробуйте еще раз.")
    except ValueError:
        print("Некорректный ввод! Попробуйте еще раз.")

arr_f = np.array([random.randint(-5, 5) for x in range(n)])
print(f"Mассив из {n} случайных чисел из диапазона [-5; 5]")
print(arr_f)

arr_f1 = []
for i in range(1, n):
    if arr_f[i - 1] == 0:
        arr_f1.append(arr_f[i])
if arr_f1 != []:
    print(max(arr_f1))
else:
    print("Нет нулевого элемента")

Введите положительное целое число:  10


Mассив из 10 случайных чисел из диапазона [-5; 5]
[ 1 -1  1  4  5  0  0 -3 -5 -1]
0


**3.** Дана целочисленная прямоугольная матрица. Определить: количество строк, не содержащих ни одного нулевого элемента, а также 
максимальное значение из чисел, встречающихся в заданной матрице более одного раза.

In [12]:
def generate_integer_matrix(rows, cols, low, high):
    matrix = np.random.randint(low, high, size=(rows, cols))
    return matrix


rows = 5  # Количество строк
cols = 5  # Количество столбцов
low = -5  # Нижняя граница
high = 5  # Верхняя граница

matrix = generate_integer_matrix(rows, cols, low, high)
print(matrix)


# Для первого условия
print("количество строк, не содержащих ни одного нулевого элемента")
print(sum(0 not in x for x in matrix))

# Для второго условия
print(
    "максимальное значение из чисел, встречающихся в заданной матрице более одного раза"
)
print(max([x for i in [[x for a in matrix for x in a]] for x in i if i.count(x) > 1]))


[[ 3 -4 -5 -5  4]
 [ 3  1 -3  4  2]
 [ 4  0  2 -5 -5]
 [ 4  1 -4 -2  0]
 [ 3  1  3 -5 -2]]
количество строк, не содержащих ни одного нулевого элемента
3
максимальное значение из чисел, встречающихся в заданной матрице более одного раза
4


**4.** Элемент матрицы называется локальным минимумом, если он строго меньше всех имеющихся у него соседей. Соседями элемента А[i,j] в матрице назовем элементы А[k,l], где i-1<=k<=i+1, j-1 < l <j+1, (k, l) != (i, j).  
Подсчитать количество локальных минимумов заданной в файле input.txt матрицы размером 10 на 10. Предусмотреть, что в файле данные могут быть введены некорректно.

In [27]:
# ready
def read_matrix_from_file(filename):
    try:
        with open(filename, "r") as file:
            matrix = []
            for line in file:
                # Преобразуем строку в список чисел
                row = list(map(int, line.split()))
                if len(row) != 10:
                    raise ValueError("Каждая строка должна содержать 10 элементов.")
                matrix.append(row)
            if len(matrix) != 10:
                raise ValueError("Матрица должна содержать 10 строк.")
            return matrix
    except Exception as e:
        print(f"Ошибка при чтении файла: {e}")
        return None


def is_local_minimum(matrix, i, j):
    current_value = matrix[i][j]
    neighbors = [
        (i - 1, j - 1),
        (i - 1, j),
        (i - 1, j + 1),
        (i, j - 1),
        (i, j + 1),
        (i + 1, j - 1),
        (i + 1, j),
        (i + 1, j + 1),
    ]

    for x, y in neighbors:
        if 0 <= x < 10 and 0 <= y < 10:  # Проверка границ матрицы
            if matrix[x][y] <= current_value:
                return False
    return True


def count_local_minima(matrix):
    count = 0
    for i in range(10):
        for j in range(10):
            if is_local_minimum(matrix, i, j):
                count += 1
    return count


def main():
    matrix = read_matrix_from_file("5-4/input.txt")
    if matrix is not None:
        local_minima_count = count_local_minima(matrix)
        print(f"Количество локальных минимумов: {local_minima_count}")
        matrix = np.array(matrix)
        print(matrix)


if __name__ == "__main__":
    main()


Ошибка при чтении файла: Матрица должна содержать 10 строк.


**5.** Определите, является ли массив магическим квадратом (суммы по всем горизонталям, вертикалям и двум диагоналям равны).

Массив является магическим квадратом.


**6.** Программным образом заполните массив одним из двух следующих способов. Размерность n и m, а также номер способа заполнения вводится пользователем при запуске программы.
Результат записать в файл.

**7.** Удалите строку и столбец, на пересечении которых находится минимальный элемент массива. После этого отсортируйте столбцы массива по неубыванию минимальных элементов в них.

## Обработка исключений. Библиотека Matplotlib

**8.**	Реализовать проверку числа 35742549198872617291353508656626642567 на простоту последовательным перебором возможных делителей (не нужен эффективный алгоритм). Выполнить замер времени работы кода без обработки исключений и с ней. Можно проводить тестирование на числе 2147483647 или 11111111111111111111111.

**9.**	В каталоге texts сохранить не менее 10 произвольных текстов объемом не менее 500 слов.  Пользователь программным образом выбирает текст. Программа строит график частоты для 50 наиболее частотных слов текста. 

**10.**	Считать данные из текстового документа, в котором написано годовое количество осадков:

*Январь 15*

*Февраль 20*

…

*Декабрь 18*


Вывести их в форме диаграмм: обычная, горизонтальная, круговая (все виды диаграмм должны быть на одном рисунке). Сохранить получившийся рисунок в файл.


**11.** Нарисовать звёздочками зелёного цвета график кардиоиды в полярной системе координат. Добавьте легенду с заголовком «Функция» и подписью «Кардиоида» в левый верхний угол.
Угол принадлежит промежутку от 0 до 3π/2, r = 2,5. Уравнение кардиоиды: ρ = 2*r*(1 + cosφ).



**12.** Написать программу изображения графика функции y=√x. Не забывайте про то, что функция имеет значения ≥ 0. Предварительно программа запрашивает у пользователя следующую информацию:

* цвет графика (программа предлагает не менее пяти различных цветов);
* тип линии (программа предлагает не менее трех различных вариантов);
* толщину линии (программа предлагает не менее пяти различных вариантов).

Все запросы к пользователю обрабатываются с использованием обработки исключительных ситуаций. Варианты можно вводить строкой или числом (на ваш выбор).
