                                                             Бояринцев Дмитрий Федорович

#                                    Лабораторная работа №5

In [1]:
import random
import numpy as np

## Массивы Numpy

**1.** Сформировать одномерный массив, состоящий из n вещественных элементов co значением от -10 до 10.0. Для случайного числа y, такого, что *минимальный элемент массива < y < максимальный элемент массива*, вычислить:  
  
* произведение элементов массива, значения модуля которых больше модуля y,  
  
* сумму модулей остальных элементов.

In [2]:
while True:
    try:
        n = int(input("Введите положительное целое число: "))
        if n > 0:
            break
        else:
            print("Число должно быть больше 0! Попробуйте еще раз.")
    except ValueError:
        print("Некорректный ввод! Попробуйте еще раз.")

array = np.random.uniform(-10, 10, n)
print("Сформированный массив:", array)

min_elem = np.min(array)
max_elem = np.max(array)

y = random.uniform(min_elem, max_elem)
print("Случайное число y:", y)

mult = np.prod(np.where(np.abs(array) > np.abs(y), array, 1))
print(f"Произведение элементов массива, модуль которых больше |y| = {mult}")

summa = np.sum(np.where(np.abs(array) <= np.abs(y), array, 0))
print(f"Сумма модулей остальных элементов = {summa}")

Введите положительное целое число:  5


Сформированный массив: [ 2.94451114 -9.45312414 -3.06756184  1.3010874  -6.93750151]
Случайное число y: -5.43489324891183
Произведение элементов массива, модуль которых больше |y| = 65.58106299859996
Сумма модулей остальных элементов = 1.1780366952758339


**2.** Найти максимальный элемент в одномерном массиве x среди элементов, перед которыми стоит нулевой.

In [4]:
while True:
    try:
        n = int(
            input("Введите положительное целое число для определения длины массива: ")
        )
        if n > 0:
            break
        else:
            print("Число должно быть больше 0! Попробуйте еще раз.")
    except ValueError:
        print("Некорректный ввод! Попробуйте еще раз.")

print(
    "Введи два числа через пробел - диапазон элементов массива [a, b]",
)
d = input().split()
x = np.random.randint(int(d[0]), int(d[1]) + 1, (n,))
print("x = ", x)
# Нахождение максимального значения элементов массива, перед которыми стоит нулевой
zero = x == 0
maximum = np.max(x[1:][zero[:-1]])
print("максимальный элемент массива, перед которым стоит нулевой = ", maximum)

Введите положительное целое число для определения длины массива:  10


Введи два числа через пробел - диапазон элементов массива [a, b]


 -5 5


x =  [ 1  0  3  3  2  2 -1 -4  4  4]
максимальный элемент массива, перед которым стоит нулевой =  3


**3.** Дана целочисленная прямоугольная матрица. Определить: количество строк, не содержащих ни одного нулевого элемента, а также 
максимальное значение из чисел, встречающихся в заданной матрице более одного раза.

In [6]:
# matrix = np.array([[4, 5, 6], [2, 9, 0], [4, 0, 7]])
# print(matrix)


def generate_integer_matrix(rows, cols, low, high):
    matrix = np.random.randint(low, high, size=(rows, cols))
    return matrix


rows = 5  # Количество строк
cols = 5  # Количество столбцов
low = -10  # Нижняя граница
high = 10  # Верхняя граница

matrix = generate_integer_matrix(rows, cols, low, high)
print(matrix)

# **Определение количества строк без нулевых элементов**
non_zero_rows_count = np.sum(~np.any(matrix == 0, axis=1))

# **Поиск максимального значения среди чисел, встречающихся более одного раза**
unique, counts = np.unique(matrix, return_counts=True)
max_value_multiple_occurrences = (
    unique[counts > 1].max() if np.any(counts > 1) else None
)

print(f"Количество строк без нулевых элементов: {non_zero_rows_count}")
print(f"Максимальное значение из чисел, встречающихся более одного раза: {max_value_multiple_occurrences}")

[[-2 -3 -1 -3  0]
 [ 9  8  6  1  7]
 [ 4  2  0  6 -7]
 [-3  0 -6 -6 -4]
 [ 3 -3 -6  7  1]]
Количество строк без нулевых элементов: 2
Максимальное значение из чисел, встречающихся более одного раза: 7


**4.** Элемент матрицы называется локальным минимумом, если он строго меньше всех имеющихся у него соседей. Соседями элемента А[i,j] в матрице назовем элементы А[k,l], где i-1<=k<=i+1, j-1 < l <j+1, (k, l) != (i, j).  
Подсчитать количество локальных минимумов заданной в файле input.txt матрицы размером 10 на 10. Предусмотреть, что в файле данные могут быть введены некорректно.

In [27]:
# ready
def read_matrix_from_file(filename):
    try:
        with open(filename, "r") as file:
            matrix = []
            for line in file:
                # Преобразуем строку в список чисел
                row = list(map(int, line.split()))
                if len(row) != 10:
                    raise ValueError("Каждая строка должна содержать 10 элементов.")
                matrix.append(row)
            if len(matrix) != 10:
                raise ValueError("Матрица должна содержать 10 строк.")
            return matrix
    except Exception as e:
        print(f"Ошибка при чтении файла: {e}")
        return None


def is_local_minimum(matrix, i, j):
    current_value = matrix[i][j]
    neighbors = [
        (i - 1, j - 1),
        (i - 1, j),
        (i - 1, j + 1),
        (i, j - 1),
        (i, j + 1),
        (i + 1, j - 1),
        (i + 1, j),
        (i + 1, j + 1),
    ]

    for x, y in neighbors:
        if 0 <= x < 10 and 0 <= y < 10:  # Проверка границ матрицы
            if matrix[x][y] <= current_value:
                return False
    return True


def count_local_minima(matrix):
    count = 0
    for i in range(10):
        for j in range(10):
            if is_local_minimum(matrix, i, j):
                count += 1
    return count


def main():
    matrix = read_matrix_from_file("5-4/input.txt")
    if matrix is not None:
        local_minima_count = count_local_minima(matrix)
        print(f"Количество локальных минимумов: {local_minima_count}")
        matrix = np.array(matrix)
        print(matrix)


if __name__ == "__main__":
    main()


Ошибка при чтении файла: Матрица должна содержать 10 строк.


**5.** Определите, является ли массив магическим квадратом (суммы по всем горизонталям, вертикалям и двум диагоналям равны).

In [5]:
def is_magic_square(matrix):
    # Преобразуем список в массив NumPy
    arr = np.array(matrix)

    # Проверка на квадратность
    n, m = arr.shape
    if n != m:
        return False

    # Вычисление магической константы
    magic_constant = np.sum(arr[0])

    # Проверка сумм строк
    if not np.all(np.sum(arr, axis=1) == magic_constant):
        return False

    # Проверка сумм столбцов
    if not np.all(np.sum(arr, axis=0) == magic_constant):
        return False

    # Проверка главной диагонали
    if np.sum(np.diag(arr)) != magic_constant:
        return False

    # Проверка побочной диагонали
    if np.sum(np.diag(np.fliplr(arr))) != magic_constant:
        return False

    return True


array = [
    [8, 1, 6],
    [3, 5, 7],
    [4, 9, 2]
]

is_magic_square(square)

if is_magic_square(square) == True:
    print("Массив является магическим квадратом")
else:
    print("Массив не является магическим квадратом")


Массив является магическим квадратом


**6.** Программным образом заполните массив одним из двух следующих способов. Размерность n и m, а также номер способа заполнения вводится пользователем при запуске программы.
Результат записать в файл.

**7.** Удалите строку и столбец, на пересечении которых находится минимальный элемент массива. После этого отсортируйте столбцы массива по неубыванию минимальных элементов в них.

## Обработка исключений. Библиотека Matplotlib

**8.**	Реализовать проверку числа 35742549198872617291353508656626642567 на простоту последовательным перебором возможных делителей (не нужен эффективный алгоритм). Выполнить замер времени работы кода без обработки исключений и с ней. Можно проводить тестирование на числе 2147483647 или 11111111111111111111111.

**9.**	В каталоге texts сохранить не менее 10 произвольных текстов объемом не менее 500 слов.  Пользователь программным образом выбирает текст. Программа строит график частоты для 50 наиболее частотных слов текста. 

**10.**	Считать данные из текстового документа, в котором написано годовое количество осадков:

*Январь 15*

*Февраль 20*

…

*Декабрь 18*


Вывести их в форме диаграмм: обычная, горизонтальная, круговая (все виды диаграмм должны быть на одном рисунке). Сохранить получившийся рисунок в файл.


**11.** Нарисовать звёздочками зелёного цвета график кардиоиды в полярной системе координат. Добавьте легенду с заголовком «Функция» и подписью «Кардиоида» в левый верхний угол.
Угол принадлежит промежутку от 0 до 3π/2, r = 2,5. Уравнение кардиоиды: ρ = 2*r*(1 + cosφ).



**12.** Написать программу изображения графика функции y=√x. Не забывайте про то, что функция имеет значения ≥ 0. Предварительно программа запрашивает у пользователя следующую информацию:

* цвет графика (программа предлагает не менее пяти различных цветов);
* тип линии (программа предлагает не менее трех различных вариантов);
* толщину линии (программа предлагает не менее пяти различных вариантов).

Все запросы к пользователю обрабатываются с использованием обработки исключительных ситуаций. Варианты можно вводить строкой или числом (на ваш выбор).
